# Generated by Django 5.0.2 on 2024-04-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=30)),
                ('kraj', models.CharField(max_length=50)),
                ('rozloha', models.IntegerField()),
                ('pocet', models.IntegerField()),
            ],
        ),
    ]
