# Generated by Django 5.0.2 on 2024-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['nazev', 'id'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.IntegerField(null=True),
        ),
    ]
