# Generated by Django 5.0.2 on 2024-04-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informace', '0002_alter_city_options_city_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
