# Generated by Django 5.0.2 on 2024-04-18 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informace', '0003_alter_city_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divadlo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=30)),
                ('umisteni', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='divadlo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='informace.divadlo'),
        ),
    ]
