# Generated by Django 5.0.2 on 2024-04-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informace', '0004_divadlo_alter_city_region_city_divadlo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divadlo',
            name='nazev',
            field=models.CharField(max_length=50),
        ),
    ]
