# Generated by Django 5.0.2 on 2024-04-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informace', '0005_alter_divadlo_nazev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('skupina', models.CharField(max_length=100)),
                ('city', models.ManyToManyField(related_name='festivals', to='informace.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='festival',
            field=models.ManyToManyField(related_name='cities', to='informace.festival'),
        ),
    ]
