# Generated by Django 5.0.2 on 2024-04-19 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informace', '0006_festival_city_festival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('strana', models.CharField(max_length=100)),
                ('mesto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='informace.city')),
            ],
        ),
    ]
