# Generated by Django 5.0.2 on 2024-04-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informace', '0007_primator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='festival',
        ),
        migrations.RemoveField(
            model_name='primator',
            name='mesto',
        ),
        migrations.DeleteModel(
            name='Festival',
        ),
        migrations.DeleteModel(
            name='Primator',
        ),
    ]
